c_stdlib_version:          # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

replacements:
  all_replacements:
    - tag: 'pkg-config build metadata'
      glob_patterns:
        - '*.pc'
      regex_re: '(?:-L|-I)?\"?([^;\s]+\/sysroot\/)'
      replacement_re: '$(CONDA_BUILD_SYSROOT_S)'
      regex_rg: '([^;\s"]+/sysroot/)'
    - tag: 'CMake build metadata'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/sysroot)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
    - tag: 'CMake build metadata OSX'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/MacOSX\d*\.?\d*\.sdk)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
