{% set name = "cartographer" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/cartographer-project/cartographer/archive/{{ version }}.tar.gz
    sha256: abba0daa348095a5e821ee5e8037bad5d06f89f4c21ea850da5ab8a7e6997a2a
    patches:
      - fix-windows.patch  # [win]
      - fix-unix.patch     # [unix]
      - fix-lua.patch
      - fix-log.patch      # [not linux]
      - fix-osx.patch      # [osx]
      - fix-static.patch   # [not win]
      - fix-testing.patch
      # necessary for ceres >=2.1
      - remove-ceres-include-dirs.patch
      - fix-werror.patch
      - fix-protobuf23.patch

build:
  number: 19

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
    - cmake
    - pkg-config
    - libprotobuf  # [build_platform != target_platform]
  host:
    - libabseil
    - ceres-solver
    - libblas
    - eigen
    - gflags
    - glog
    - lua
    - cairo
    - glib
    - libboost-devel
    - gtest
    - gmock
    - libprotobuf
    - xorg-libx11      # [unix]
    - xorg-libxext     # [unix]
    - xorg-libxrender  # [unix]
    - xorg-libxau      # [unix]

  run:
    - xorg-libx11      # [unix]
    - xorg-libxext     # [unix]
    - xorg-libxrender  # [unix]
    - xorg-libxau      # [unix]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\cartographer.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cartographer.dll exit 1  # [win]

about:
  home: https://github.com/cartographer-project/cartographer
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Cartographer is a system that provides real-time simultaneous localization and mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
